name: Update README with GitHub Pages URL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository information
        id: repo-info
        run: |
          echo "username=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "reponame=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Update README with GitHub Pages URL
        run: |
          GHPAGES_URL="https://${{ env.username }}.github.io/${{ env.reponame }}"
          sed -i "s|INSERT_GHPAGES_URL_HERE|$GHPAGES_URL|g" README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with GitHub Pages URL" || echo "No changes to commit"
          git push
